[functions]
directory = "netlify/functions"

[build]
command = "npm install"
functions = "netlify/functions"
publish = "public"

[[redirects]]
from = "/api/tests*"
to = "/.netlify/functions/tests"
status = 200
force = true

[[redirects]]
from = "/api/users*"
to = "/.netlify/functions/users"
status = 200
force = true

[[redirects]]
from = "/api/stats"
to = "/.netlify/functions/queries/stats"
status = 200
force = true

[[redirects]]
from = "/api/questions*"
to = "/.netlify/functions/queries/:splat"
status = 200
force = true
